print("hola mundo!")
print("Este coronavirus es imparable \n todo los dias se enferman las personas.")
print("La Witsi Witsi Arañar" , "subió" , "a su telaraña.")
print("Mi nombre es", "Python.", end="\n")
print("Monty Python.")
print("Mi nombre es", "Python.", end="")
print("Monty Python.")
print("Mi", "nombre", "es", "Monty", "Python.", sep="-")
print("Mi", "nombre", "es", sep="_", end="*")
print("Monty", "Python.", sep="*", end="*\n")
